config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  resources :users
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # バリデーション
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :comment, presence: true, length: { maximum: 1000 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :user_id, presence: true
  validates :book_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # バリデーション
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  def after_sign_in_path_for(resource)
    user_path(resource)
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :introduction])
    devise_parameter_sanitizer.permit(:sign_in,keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:introduction])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_to request.referer
  end


  private

  def post_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @new_book = Book.new
    @user = current_user
  end


  def create
    @item = Book.new(book_params)
    @item.user_id = current_user.id
    if @item.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@item.id)
    else
      @books = Book.all
      @new_book = Book.new
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @new_commnet = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @item = Book.find(params[:id])
    if @item.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@item.id)
    else
      @book = Book.find(params[:id])
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @user = current_user
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end

  end

  def update
    @item = User.find(params[:id])
    if @item.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@item.id)
    else
      @user = @item
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

		  <h1>Editing Book</h1>

		  <%= render 'layouts/errors', obj: @item %>

		  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>

  		<%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @item %>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render partial: '/layouts/post', locals: { user: @user, new_book: @new_book } %>

    <div class="col-md-8 offset-md-1">
		  <h2>Books</h2>
		  <table class="table">
		    <tbody>
		      <% @books.each do |list| %>
          <tr>
            <td><a href=<%= user_path(list.user_id) %>>
              <%= image_tag @user.get_profile_image(80, 80) %>
            </a></td>
            <td><%= link_to list.title, book_path(list.id) %></td>
            <td><%= list.body %></td>
            <td>
              <% if list.favorited_by?(current_user) %>
                <a href=<%= book_favorites_path(list.id) %> data-method="delete"><i class="fas fa-heart" style="color: red;"></i><%= list.favorites.count %></a>
              <% else %>
                <a href=<%= book_favorites_path(list.id) %> data-method="post"><i class="fas fa-heart" style="color: blue;"></i><%= list.favorites.count %></a>
              <% end %>
            </td>
            <td>コメント数:<%= list.book_comments.count %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render partial: '/layouts/post', locals: { user: @user, new_book: @new_book } %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table"><tbody>

		    <tr>
          <td><a href="<%= user_path(@user.id) %>">
            <%= image_tag @user.get_profile_image(80, 80) %><br>
            <%= @book.user.name %>
          </a></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <a href=<%= book_favorites_path(@book.id) %> data-method="delete"><i class="fas fa-heart" style="color: red;"></i><%= @book.favorites.count %></a>
            <% else %>
              <a href=<%= book_favorites_path(@book.id) %> data-method="post"><i class="fas fa-heart" style="color: blue;"></i><%= @book.favorites.count %></a>
            <% end %>
          </td>
          <td>コメント数:<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-sm btn-danger' %></td>
          <% end %>
        </tr>

        <% @book.book_comments.each do |comment| %>
          <tr>
            <td><a href=<%= user_path(comment.user.id) %>>
              <%= image_tag comment.user.get_profile_image(80, 80) %><br>
              <%= comment.user.name %>
            </a></td>
            <td><%= comment.comment %></td>
            <% if comment.user == current_user %>
              <td><%= link_to "Destroy", book_book_comment_path(@book, comment), method: :delete, data: { confirm: "本当に消しますか？" }, class: 'btn btn-sm btn-danger' %></td>
            <% end %>
          </tr>
        <% end %>


      </tbody></table>
      <%= form_with model: @new_commnet, url: book_book_comments_path(@book.id), method: :post do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows: '5' ,class: 'w-100' %>
        </div>
        <%= f.submit '送信', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path , class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path , class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if defined? obj.errors %>

  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/layouts/_post.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100, 100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <a class="btn btn-outline-secondary btn-block edit_user_51900" href=<%= edit_user_path(user.id) %>><i class="fas fa-user-cog"></i></a>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: new_book, url: books_path, method: :post do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label><br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label><br>
      <%= f.text_area :body %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <a class="nav-link text-light" href=<% user_path(current_user.id) %>><i class="fas fa-home"></i>Home</a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users"><i class="fas fa-users"></i>Users</a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/books"><i class="fas fa-book-open"></i>Books</a>
                </li>
                <li>
                  <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"><i class="fas fa-sign-out-alt"></i>Log out</a>
                </li>
              <% else %>
                <li>
                  <a class="nav-link text-light" href="/"><i class="fas fa-home"></i>Home</a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/home/about"><i class="fas fa-link"></i>About</a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_up"><i class="fas fa-user-plus"></i>Sign up</a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_in"><i class="fas fa-sign-in-alt"></i>Log in</a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>

      <% flash.each do | name, msg | %>
        <%= content_tag :div, msg, class: name %>
      <% end %>

      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

    <%= render 'layouts/errors', obj: @item %>

    <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>

        <div class="field">
          <label>Name</label><br>
          <%= f.text_field :name, autofocus: true %>
        </div>
        <div class="field">
          <label>Image</label><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="field">
          <label>Introduction</label><br>
          <%= f.text_area :introduction %>
        </div>

        <div class="actions">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>
    <% end %>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/errors', obj: @item %>

<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render partial: '/layouts/post', locals: { user: @user, new_book: @new_book } %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |u| %>
            <tr>
              <td><%= image_tag u.get_profile_image(80, 80) %></td>
              <td><%= u.name %></td>
              <td><%= link_to "Show", user_path(u.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render partial: '/layouts/post', locals: { user: @user, new_book: @new_book } %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |list| %>
            <tr>
              <td><a href="<%= user_path(@user.id) %>">
                <%= image_tag @user.get_profile_image(80, 80) %>
              </a></td>
              <td><%= link_to list.title, book_path(list.id) %></td>
              <td><%= list.body %></td>
              <td>
                <% if list.favorited_by?(current_user) %>
                  <a href=<%= book_favorites_path(list.id) %> data-method="delete"><i class="fas fa-heart" style="color: red;"></i><%= list.favorites.count %></a>
                <% else %>
                  <a href=<%= book_favorites_path(list.id) %> data-method="post"><i class="fas fa-heart" style="color: blue;"></i><%= list.favorites.count %></a>
                <% end %>
          </td>
              <td>コメント数:<%= list.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>